[tool.poetry]
name = "sfdl-sample-pyodide"
version = "0.1.0"
description = "Sample build for pyodide"
authors = ["dotloadmovie"]

[tool.poetry.dependencies]
python = "^3.10"
rpc-wrap = "^0.3.0"
build = "^0.9.0"
